### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by KvenLee** [chiuan/TTUIFramework#1]
大神，我看了一下你的TTUIPage的整体结构，感觉十分的清晰，所以将你的框架用到了我们的项目中，目前UI的进展还是很顺利的，你的UIBinder中的异步加载绑定那个是不是还没开始写啊~能够留下联系方式，多多交流~~

**Comment by chiuan** [comment]
@KvenLee  你说的异步加载绑定指是什么？框架支持同步异步加载UI。我现在项目也在用着是异步的UI加载。qq  121238591
