### ISSUE TITLE
Could you please support transition event

### ISSUE THREAD

**Issue by takaaptech** [chiuan/TTUIFramework#5]
Hi,
I found this framework is awesome!
Could you please add some function so the transition between page will be easier. For example, we will have OnPageAnimationStart, OnPageAnimation, OnPageAnimationFinished for both In and Out process?
That way we can have smooth page switch effect.
Thank so much!

**Comment by chiuan** [comment]
that's good point. i am thinking how to make it easy and simple. because i have working on the other thing. so time is limited. maybe need some days.
thanks for the good advice.

**Comment by GqLabs** [comment]
数据更新是个问题，必须用TTUIPage.ShowPage<T>(object pageData) 传入再刷新，直接刷新时传入比较好

**Comment by GqLabs** [comment]
UI的事件注册你最好也封装一下，就像Button的onClick.AddListener()和onClick.RemoveAllListeners()。这些就很好用

**Comment by chiuan** [comment]
@GqLabs 你理解错了. 这些用什么UI.怎么监听. 自己的事情.不是这块考虑

**Comment by GqLabs** [comment]
@chiuan 看看这个http://www.xuanyusong.com/archives/3325  你的QQ或微信能告诉我吗？详细聊一下

**Comment by chiuan** [comment]
@GqLabs 你还没理解这个东西做的事情.
