### ISSUE TITLE
重写TTUIPage.Hide()时发现一个疑问

### ISSUE THREAD

**Issue by oOtroyOo** [chiuan/TTUIFramework#7]
当我重写TTUIPage.Hide() ，想延时再隐藏

原文是
```
        public virtual void Hide()
        {
            this.gameObject.SetActive(false);
            isActived = false;
            //set this page's data null when hide.
            this.m_data = null;
        }
```

重写之后是

```
        public override void Hide()
        {
            Tweener doFade = this.gameObject.GetComponent<CanvasGroup>().DOFade(0, 0.5f);
            doFade.onComplete += () => this.gameObject.SetActive(false);

            isActived = false;
            //set this page's data null when hide.
            this.m_data = null;
        }
```
问题在于

-  `this.m_data` 是private，此处报错。是否应该将其设置为protected 。

- 已经具有一个protected的封装成员 ` protected object data { get { return m_data; } }` ，但是它并没有set访问器

- 以为我需要延时隐藏，所以不能直接调用`base.Hide()`。因为里面有`gameObject.SetActive(false);`

- 是否应该将 `gameObject.SetActive(false)`与  `this.m_data = null;` 分成2个方法来调用

**Comment by chiuan** [comment]
是这样的,你大概是关闭时候需要表演吧.

1 - 看了下你的思路,我感觉你还需要缓存一下你的doFade,在复写的OnShow时候如果这个还在执行,就dispose掉.你要考虑关闭的这个表演过程中,马上重新打开.

2 - m_data实际上是关闭后清掉页面传参. 你可以不清也可以(因为实际上每次打开都会新的参数进来),这里清掉为了更好gc. 也可以改成protected,你觉得方便都可以.
